# Generated by Django 4.2.3 on 2023-07-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Backlog', 'Backlog'), ('Done', 'Done'), ('In Progress', 'In Progress')], default='Open', max_length=20),
        ),
    ]
